name: Docker Image Build

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths-ignore:
      - "**/README.md"
      - "**/LICENSE"
      - "**/docker-compose.yml.example"
      - "**/config.yml.example"
      - "**/.dockerignore"
      - "**/.gitignore"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup builder
        run: docker run --privileged --rm tonistiigi/binfmt --install all
      - run: docker buildx create --name builder --driver docker-container --platform linux/amd64,linux/arm64 --use
      - run: docker buildx inspect --bootstrap

      - name: Build image and push(py3.9)
        run: docker buildx build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:py3.9 --platform linux/amd64,linux/arm64 --progress plain --push -f dockerfiles/py3.9/Dockerfile .

      - name: Build image and push(py3.10)
        run: docker buildx build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:py3.10 --platform linux/amd64,linux/arm64 --progress plain --push -f dockerfiles/py3.10/Dockerfile .

      - name: Build image and push(py3.11)
        run: docker buildx build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:py3.11 --platform linux/amd64,linux/arm64 --progress plain --push -f dockerfiles/py3.11/Dockerfile .

      - name: Build image and push(py3.12)
        run: docker buildx build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:py3.12 --platform linux/amd64,linux/arm64 --progress plain --push -f dockerfiles/py3.12/Dockerfile .
